sudo: required

language: go

go:
  - 1.8

services:
  - docker

cache:
  directories:
    - backend/vendor/github.com
    - backend/vendor/go4.org
    - backend/vendor/golang.org
    - backend/vendor/gopkg.in

env:
  global:
    - CGO_ENABLED=0
    - GOBUILD="linux-amd64 windows-amd64 darwin-amd64"
    # DOCKER_USER
    - secure: "oHf0V+Znh5TzZeoFQ6Y7npSkwZEyFinOj9vGTznphqJfh45CrvDQVP/3BkqGLGeIUY7WiR+CkdY4Zu6pMgjXOxria5cz9+qgU9suBplATDRjnVfvEZXABpJkq2Opk0EZ4TxwAkSTYcpjy3DQcjBAhfOWQeIZPfYAQfRAJ9QDlhULWnjSuuNjvJ1H/M9Hv3HtLcfXEGDmvXeczgf5mistJpiw+Csn9rgDniSBPUe6w2REQM/vSBiqPQYUBYKx6dDCFvY5KWd3H2s+w4JA0B/f7/zMHot5at9Feea7WXxCbH8/gnRepCdO8DRHSTCmV55S9co5kJbD6vL1DVhSY9MLAh8atyoCqHILiOzPh95v/nnAkP5RTyrjBbfQkilwdn1el0vzW9i4iGvUU5AMdqqv7/6lobHYcfEaOPaIRBc+rRy5DJmvxKBrxFC+mChzloJNaZVU8UkSXYaLcAw8BgR2qrgIN5QBjqO+fX+4oOpoEs2Rp/0MSMp8FT8Cb7wWbd0tJOu654W7nUO3FSfU6qFKrnHqN0xjopC0hILh+iYd4bHOV4HhxUvPLiTdsmWslgy+770eZGlQufW6YgNwBgn/JS7c8/WTO5oBKEs9nD3EqvyEZepa/2KnAAVpGxCRf0NyWc/awCSLUev1fTnR0N0w1izLQdc95YoWHUJocuuF+no="
    # DOCKER_PASS
    - secure: "FRxJAUBYHcNSu5Z7wNxIhZdS6TUmZTeAUU0XerydjXjSlldOlD2dc9cSy9gmJvMz82wmCHaDDVeH711oUSe3gKj8N+4zL0Pnu4NerWws5LWnA7nzsdA/2Yfu6/Y+wg2VEkhdeQ3BKDNdHTePYSBXvn1n/xGX/ZIiMNzsh3iGplpjI3WY7LOF9+DhvZa9b8vnAPTfYCweKKLSnql8J6Ytu6bWuxybBkyP9grDTn+UnOGp4RXuqSFdoF9I89qmlPCCfnRU/DHcTfNPrl36pI8/n8ypsJkezALKpPzO86fmeMUUbBH03UZIgV3Q3wDmp1XsK+OpbwFAUoT28u9toYu82tn/u3jWXssRBmedRGxRyIutzhkZ41s2TSSkCqF5DXt/7KgBhBDDPTb/ZuIjmjlK/ENQzcMpggaI/ZJtRZwwb/geVJrcl+BHaz8t+ZVjFCAtn+V1AaxMYafW5CJkugh6gHwkUWGpWUNdhl3b7DsvB1bw485I+Wqo6KuzTBnhIUEnFWcb08EZfPMwhBKOwVlzfHCpJi0Lh6ppCVO91DGoUAzM3uDfDKEU5xSc+MAafC3B0dUfKtzMZmGBjbqeVoDyArmtEWYJjxZB9nMEGT5CIgkOkTA3e1KzJDg+MvK+kQpU2bRTmnW2HGeSi9Oxo9woYM6z0Lb2Mw7nqPRbAJqHG5Q="

script:
  - GOBUILD=${GOBUILD} make -j dist
  - ls -la build

after_success:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$TRAVIS_TAG" =~ ^v.*$ ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=latest COMMIT=$TRAVIS_COMMIT; fi

deploy:
  provider: releases
  api_key:
    secure: iUEYgokutOO6dve8VEB6ZGzq2zaSczgg16HN01/Wb3R2j+YGwdm7Gwy9xB/QdEz9UPdBhZSpKzT6MzI3HCt5YliBdrbEsV3QTuLR5yVDegDwBpfHwxA+R8VjXKJPi65HZhnmCmsxhDwzPn1B01nzQVRvSz8hR/5J0Y+L6h37V10niuK0b5bsopucfyTvrhIZRoWVjvDOMJSiV4g9smEbPE3egdlLP+GEezIE2daSUdGdnfpVJk2VqfrHCU6n0gz1Dpv0+fSkGg/ypbNBmTOu4jnfklXuUhqdyLAr+gJW3bNnZDNVBK/Fa8Mp5kOKrPwGdbPfrjUo0KHipT3caDIGGAzgQZF21CiWzXOmzyW1cUXAO1OhFG8ZJNnyWFQ7dbxjTN5meyEOvTaxDi4rECsjblFj5m6JaexQwDy9lC1wm5vDxTC9dVG/ZcEXgtGOfJu/qOw44Bj/MIomc1mxVCjVB82MZBkUopGXRDm+kDSWkmXlD/NIUV00t6i7q33AkR0rCMqg7f/a5yHp/AlCR6mH/8PQe9GLxBrCUq2ufzLZmA9valRr/5/H8KQvDPhDI10+Df8fusBfH/iLKUOjC9TCN9at1KUQOvS467sM/nJSI0XsotWFGalkyytogfMxaXzuwSob/YgGf1aGTXmjjubiM96YHF8cUVLC623gGAHBoeQ=
  file:
    - build/aws-dynamic-consul-catalog-linux-amd64
    - build/aws-dynamic-consul-catalog-windows-amd64
    - build/aws-dynamic-consul-catalog-darwin-amd64
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: seatgeek/aws-dynamic-consul-catalog
