sudo: required

language: go

go:
  - "1.11"

services:
  - docker

cache:
  directories:
    - vendor/github.com
    - vendor/go4.org
    - vendor/golang.org
    - vendor/gopkg.in

env:
  global:
    - CGO_ENABLED=0
    - GOBUILD="linux-amd64 darwin-amd64"
    # DOCKER_USER
    - secure: "oHf0V+Znh5TzZeoFQ6Y7npSkwZEyFinOj9vGTznphqJfh45CrvDQVP/3BkqGLGeIUY7WiR+CkdY4Zu6pMgjXOxria5cz9+qgU9suBplATDRjnVfvEZXABpJkq2Opk0EZ4TxwAkSTYcpjy3DQcjBAhfOWQeIZPfYAQfRAJ9QDlhULWnjSuuNjvJ1H/M9Hv3HtLcfXEGDmvXeczgf5mistJpiw+Csn9rgDniSBPUe6w2REQM/vSBiqPQYUBYKx6dDCFvY5KWd3H2s+w4JA0B/f7/zMHot5at9Feea7WXxCbH8/gnRepCdO8DRHSTCmV55S9co5kJbD6vL1DVhSY9MLAh8atyoCqHILiOzPh95v/nnAkP5RTyrjBbfQkilwdn1el0vzW9i4iGvUU5AMdqqv7/6lobHYcfEaOPaIRBc+rRy5DJmvxKBrxFC+mChzloJNaZVU8UkSXYaLcAw8BgR2qrgIN5QBjqO+fX+4oOpoEs2Rp/0MSMp8FT8Cb7wWbd0tJOu654W7nUO3FSfU6qFKrnHqN0xjopC0hILh+iYd4bHOV4HhxUvPLiTdsmWslgy+770eZGlQufW6YgNwBgn/JS7c8/WTO5oBKEs9nD3EqvyEZepa/2KnAAVpGxCRf0NyWc/awCSLUev1fTnR0N0w1izLQdc95YoWHUJocuuF+no="
    # DOCKER_PASS
    - secure: "FRxJAUBYHcNSu5Z7wNxIhZdS6TUmZTeAUU0XerydjXjSlldOlD2dc9cSy9gmJvMz82wmCHaDDVeH711oUSe3gKj8N+4zL0Pnu4NerWws5LWnA7nzsdA/2Yfu6/Y+wg2VEkhdeQ3BKDNdHTePYSBXvn1n/xGX/ZIiMNzsh3iGplpjI3WY7LOF9+DhvZa9b8vnAPTfYCweKKLSnql8J6Ytu6bWuxybBkyP9grDTn+UnOGp4RXuqSFdoF9I89qmlPCCfnRU/DHcTfNPrl36pI8/n8ypsJkezALKpPzO86fmeMUUbBH03UZIgV3Q3wDmp1XsK+OpbwFAUoT28u9toYu82tn/u3jWXssRBmedRGxRyIutzhkZ41s2TSSkCqF5DXt/7KgBhBDDPTb/ZuIjmjlK/ENQzcMpggaI/ZJtRZwwb/geVJrcl+BHaz8t+ZVjFCAtn+V1AaxMYafW5CJkugh6gHwkUWGpWUNdhl3b7DsvB1bw485I+Wqo6KuzTBnhIUEnFWcb08EZfPMwhBKOwVlzfHCpJi0Lh6ppCVO91DGoUAzM3uDfDKEU5xSc+MAafC3B0dUfKtzMZmGBjbqeVoDyArmtEWYJjxZB9nMEGT5CIgkOkTA3e1KzJDg+MvK+kQpU2bRTmnW2HGeSi9Oxo9woYM6z0Lb2Mw7nqPRbAJqHG5Q="

script:
  - GOBUILD=${GOBUILD} make -j dist
  - ls -la build

after_success:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$TRAVIS_TAG" =~ ^v.*$ ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=latest COMMIT=$TRAVIS_COMMIT; fi

deploy:
  provider: releases
  api_key:
    secure: Q5+xBeDLU/gdalRVhniTrmmR0Afq9w3Vni1RUwGhTAGSJK2kzO7Jz+Khvle63KbW67l0EoNIvpOxatKgx5wq0qiOwH4pSKkY6+hmqxY6bU73RNQBp/pXarxuQ9WiXHI3AditGxO4kVMXaB6pFi1GDb/L+yELR0cZ6PYRMEHUzi23+bVyI9Ky+1fERkwqOS2qMXNDKeSy2I27GbLvlRbsMksgBr3/q6c4By9LQfMgFUhwbzEM1DZaVk42cSlEXRM5zo+nhD7+nK335C+rheCYla4vJW8H+N2DJj7FM05Ve7vCwuC1Mw4OqsqnjdCIiPw1DXX7ZGOfsAQPwankWa2tI8cT7JX2h9+NhP5iEB7CBeukcUvsFD84mGipPrDGhZnCX/tjGrvi9ISjP4cdzWsxEqb3GSuI6n5t/f43qLjQv5dFnuMCLNl3m2CmFr1ICMMq2Gx8Us6z/mmQTfZUV9CfynKTOL1B15ugsuGlE4GinsjBEFXeu7Hg5U8vVgRjfcrdyBMfH0XjPMl91t4QtbYeZWFOIvVvcEVHGmTcHCUetJeG+3UJrHLVAgeTRFaOZQoiucq6xaoy7/BxC0St5TvI1DugpD3V0hQ5eCrfsOn2cRLHp81vdpMPV0CL0+ay99blINFcD4q+T4BStf9CljGG5QEQaDwraszWsmzcRK2jF28=
  file:
    - build/aws-dynamic-consul-catalog-linux-amd64
    - build/aws-dynamic-consul-catalog-darwin-amd64
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: seatgeek/aws-dynamic-consul-catalog
